import type {NextPage} from 'next'
import Head from 'next/head'
import {trpc} from '../utils/trpc'
import {useSession, signIn, signOut} from 'next-auth/react'
// import Navbar from '../components/Navbar'

import Search from '../components/Search'

const Home: NextPage = () => {
    const {data: session} = useSession()

    return (
        <>
            <Head>
                <title>Progetit</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {session && (
                <div className="relative w-screen h-screen flex flex-row justify-center text-midnight-100"></div>
            )}
            {!session && (
                <div>
                    Not signed in <br />
                    <button onClick={() => signIn()}>Sign in</button>
                </div>
            )}
            {/* //  */}
        </>
    )
}

export default Home
