import type {NextPage} from 'next'
import Head from 'next/head'
import {trpc} from '../utils/trpc'

import Sidebar from '../components/Sidebar'
import Main from '../components/Main'
import Search from '../components/Search'

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Progetit</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="relative w-screen h-screen flex flex-row justify-center text-midnight-100">
                <Sidebar />
                <Main></Main>
                <Search />
            </div>
        </>
    )
}

export default Home
